version: '3.8'

services:
  adminer:
    image: 'adminer:4.8.1-standalone'
    hostname: adminer
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN}`)'
      - 'traefik.http.services.adminer.loadbalancer.server.port=8080'

networks:
  proxy:
    external: true
