version: '3.8'
services:
  nextjs-prisma-prod:
    container_name: nextjs-prisma-prod
    image: nemanjamitic/nextjs-prisma-boilerplate:latest
    # ports:
    #   - '3001:3001'
    #command: sleep infinity
    volumes:
      - ./uploads:/app/uploads
      # uncomment for external access
      # - ./prisma/pg-config/pg_hba.conf:/etc/postgresql.conf
      # - ./prisma/pg-config/postgresql.conf:/etc/pg_hba.conf
    env_file:
      - .env.production
      # for now
      - .env.local
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.nextjs-prisma-secure.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.nextjs-prisma-secure.entrypoints=websecure'
      - 'traefik.http.routers.nextjs-prisma-secure.service=nextjs-prisma-svc'
      - 'traefik.http.services.nextjs-prisma-svc.loadbalancer.server.port=3001'
    depends_on:
      - postgres-db-prod
    networks:
      - proxy

  postgres-db-prod:
    image: postgres:14-alpine
    container_name: postgres-db-prod
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    env_file:
      - .env.local
    networks:
      # for adminer
      - proxy

networks:
  proxy:
    external: true
