version: '3.8'
services:
  postgres-external:
    image: postgres:14-alpine
    container_name: postgres-external
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - '5433:5433'
    env_file:
      - .env.local
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-config/postgresql.conf:/etc/postgresql.conf
      - ./pg-config/pg_hba.conf:/etc/pg_hba.conf
    networks:
      - proxy

networks:
  proxy:
    external: true
